export { default as HeroImage1 } from "./highway-istanbul.jpg";
export { default as SomoLogo } from "./somoLogo.png";
export { default as TruckImg } from "./truck.jpeg";
export { default as LadyImg } from "./female-truck-driver-working.jpg";
export { default as Frontview } from "./front-view-man-holding-clipboard.jpg";
export { default as FleetImg } from "./modern-truck-fleet.jpg";
export { default as TrackingImg } from "./gps-tracking-system.jpg";
export { default as MaintenanceImg } from "./vehicle-maintenance.jpg";
export { default as SafetyImg } from "./safety-inspection.jpg";
export { default as ClientsImg } from "./client-partnerships.jpg";
export { default as EmergencyImg } from "./emergency-response-team.jpg";
export { default as ImpressedImg } from "./impressed.jpg";
export { default as TruckImg1 } from "./TruckImg.jpg";
export { default as TruckImg2 } from "./TruckImg2.jpg";
export { default as TruckImg3 } from "./TruckImg3.jpg";
export { default as TruckImg4 } from "./TruckImg4.jpg";
export {default as ContactBgImg} from "./contactus.jpg";
//with real images
export {default as RealImg} from './real1.jpg';
export {default as OurStory} from './Ourstory.jpeg';